service: cs3219-task-b
provider:
 name: aws
 runtime: nodejs12.x
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-2
 apiGateway:
  shouldStartNameWithService: true

functions:
 api:
   handler: lambda.universal
   events:
     - http: 
         path: /
         method: ANY
         cors: true
     - http:
         path: /{proxy}
         method: ANY
         cors: true
         

